--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.890.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023. 11. 08. 17:09:45
-- Server version: 8.0.27
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE film;

--
-- Drop table `film`
--
DROP TABLE IF EXISTS film;

--
-- Set default database
--
USE film;

--
-- Create table `film`
--
CREATE TABLE film (
  id INT NOT NULL AUTO_INCREMENT,
  rendezo VARCHAR(64) NOT NULL,
  cim VARCHAR(128) NOT NULL,
  ev INT DEFAULT NULL,
  nyelv VARCHAR(50) DEFAULT NULL,
  hossz INT DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 1489,
CHARACTER SET utf16,
COLLATE utf16_hungarian_ci;

-- 
-- Dumping data for table film
--
INSERT INTO film VALUES
(1, 'Alfred Hitchcock', 'Mentőcsónak\r\nxxx', 1943, 'angol', 92),
(2, 'Woody Allen', 'Játszd újra, Sam', 1972, 'angol', 94),
(3, 'Andrej Tarkovszkij', 'Solaris', 1972, 'orosz', 180),
(4, 'Jancsó Miklós', 'Oldás és kötés\r\n', 1963, 'magyar', 120),
(5, 'Kovács András', 'Októberi vasárnap', 1978, 'magyar', 110),
(6, 'Fábri Zoltán', 'A tanú', 1969, 'magyar', 103);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;